Recommend graphql-http instead of deprecated express-graphql
graphql/graphql.github.io pull request #1616
Opened 2024-01-26 16:58 UTC by enisdenjo

Closes #1607

Note that graphql-http does not ship with GraphiQL integration since it's purely a reference implementation of the transport, so I've just removed it.

However, I plan on having a plugin/mod thing that adds easy integration to graphql-http. When that's done, I'll revise the docs here.

Alternatively, a CLI of sorts for [`graphiql`](https://github.com/graphql/graphiql) would be top notch ([similar to what `ruru` offers](https://github.com/graphile/crystal/tree/main/grafast/ruru)). @acao thoughts?

2024-01-31 13:00 UTC, benjie requested changes
Looking good!

2024-01-31 13:00 UTC, benjie commented on src/content/graphql-js/APIReference-ExpressGraphQL.md
> -See the [GitHub README](https://github.com/graphql/express-graphql) for more extensive documentation of the details of this method.
Rather than deleting this page (I'm a believer in stable URLs), could you add a note to the top that this has been replaced by GraphQL-HTTP?

2024-01-31 13:00 UTC, benjie commented on src/content/graphql-js/APIReference-GraphQLHTTP.md
> +The [official `graphql-http` package](https://github.com/graphql/graphql-http) provides a simple way to create an [Express](https://expressjs.com/) server that runs a GraphQL API.
You should comment that it's more than just Express

2024-01-31 13:00 UTC, benjie commented on src/content/graphql-js/APIReference-GraphQLHTTP.md
> +See the [GitHub README](https://github.com/graphql/graphql-http) for more extensive documentation of the details of this method.
```suggestion
See the [GitHub README](https://github.com/graphql/graphql-http) for more extensive documentation, including how to use `graphql-http` with other server frameworks.
```

2024-01-31 13:00 UTC, benjie commented on src/content/graphql-js/Guides-ConstructingTypes.md
> +next: /graphql-js/express-http/
```suggestion
next: /graphql-js/graphql-http/
```

2024-01-31 13:00 UTC, benjie commented on src/content/graphql-js/Tutorial-ExpressGraphQL.md
> +At this point you have learned how to run a GraphQL server. The next step is to learn how to [issue GraphQL queries from client code](/graphql-js/graphql-clients/).
It is a shame about the loss of GraphiQL here, as you say. This is a very natural point where someone would want a low-effort way of testing their API. Perhaps you could recommend a standalone GraphQL client to use to test it here, such as Altair, Playground, Postman, Ruru, etc?

Alternatively, you could add Ruru to the express server easily:

```ts
import { ruruHTML } from "ruru/server";

app.get("/", (req, res, next) => {
  res.type("html");
  res.end(ruruHTML({ endpoint: "/graphql" }));
});
```

2024-01-31 13:00 UTC, benjie commented on vercel.json
> +      "destination": "/graphql-js/graphql-http/",
Ah you're redirecting the old URL? You can probably ignore my previous comment then :+1:

2024-01-31 13:00 UTC, benjie commented on src/content/graphql-js/APIReference-ExpressGraphQL.md
> -See the [GitHub README](https://github.com/graphql/express-graphql) for more extensive documentation of the details of this method.
(Looks like you've set up a redirect, so you can probably ignore this.)

2024-02-02 16:03 UTC, enisdenjo commented on src/content/graphql-js/APIReference-GraphQLHTTP.md
> +The [official `graphql-http` package](https://github.com/graphql/graphql-http) provides a simple way to create an [Express](https://expressjs.com/) server that runs a GraphQL API.
https://github.com/graphql/graphql.github.io/pull/1616/commits/f4e163240085d6e5ed1b5de57d47c70e222ac0ac

2024-02-02 16:14 UTC, enisdenjo commented on src/content/graphql-js/Tutorial-ExpressGraphQL.md
> +At this point you have learned how to run a GraphQL server. The next step is to learn how to [issue GraphQL queries from client code](/graphql-js/graphql-clients/).
[ruru it is!](https://github.com/graphql/graphql.github.io/pull/1616/commits/e89665feb024fd7662d596bdd30273137cee1e5d)

2024-02-14 10:31 UTC, benjie approved these changes
Looks good to me; thanks @enisdenjo!

2024-02-14 11:12 UTC, benjie commented
@graphql/tsc I won't merge this myself since it suggests adding `ruru` which is one of my (MIT-licensed, open source) projects - if you're happy with the suggestion please merge, otherwise please suggest an alternative.

2024-02-14 12:50 UTC, Urigo commented
awesome work!

2024-02-14 12:50 UTC, merged