fix registration links
graphql/graphql.github.io pull request #1704
Opened 2024-05-19 15:20 UTC by YassinEldeeb

2024-05-20 09:47 UTC, Urigo commented
@YassinEldeeb @jorydotcom I think the header is way over populated
<img width="1462" alt="image" src="https://github.com/graphql/graphql.github.io/assets/1297448/efa22d22-15f6-44e9-867d-5dfc1951d7ef">
Maybe we can find a better design solution for this?

2024-05-20 09:59 UTC, YassinEldeeb commented
ah, I didn’t think it’d wrap with smaller screens.

Is the register button really needed in the nav? I think the button in the hero section acts is a pretty good call to action.

2024-05-20 10:01 UTC, YassinEldeeb commented
oh, I think we can remove the “Register” link in the navbar, it’s redundant, it takes the user to cvent, which we don’t want.

2024-05-20 10:13 UTC, YassinEldeeb commented
ok, @Urigo how about now?

2024-05-20 15:12 UTC, jorydotcom commented
@YassinEldeeb The Conference Committee met this morning and we discussed the nav issue you & @Urigo highlighted. They have requested that:

- The GraphQLConf 2023 link move to the footer
- We drop the 'Speakers' item for the time being, since we don't have anything announced
- We make the 'Register' link an anchor tag to the "Pricing and Registration" section of the homepage

They also want to combine the Partner and Sponsor pages, but I think that's a bigger PR. The group was unanimous though that we should _not drop_ 'Register' from the top nav.

2024-05-20 15:13 UTC, jorydotcom requested changes
See https://github.com/graphql/graphql.github.io/pull/1704#issuecomment-2120661483

2024-05-20 16:54 UTC, YassinEldeeb commented
Thanks for your feedback @jorydotcom! I’ll apply the proposed changes in this PR.

2024-05-21 10:14 UTC, YassinEldeeb commented
@Urigo @jorydotcom can you please review the current state of the PR? I have applied your suggestions.

2024-05-21 16:30 UTC, Urigo commented
Looks much better to me
@jorydotcom can you give it another review and also maybe ping the marketing team?

2024-05-23 12:59 UTC, jorydotcom commented
It looks so much better!! Thank you @dimaMachina !!!! <3

2024-05-23 12:59 UTC, jorydotcom approved these changes

2024-05-23 13:34 UTC, Urigo commented
@YassinEldeeb one last comment, if I'm not on the main page and I click "Register", it doesn't do anything

2024-05-23 13:41 UTC, YassinEldeeb commented on src/app/conf/2024/layout.tsx
> +          { children: <span>Register</span>, href: "#attend" },
```suggestion
          { children: <span>Register</span>, href: "/conf/2024#attend" },
```

2024-05-23 13:41 UTC, YassinEldeeb commented
@Urigo fixed it

2024-05-23 13:48 UTC, Urigo commented
thank you!

2024-05-23 13:48 UTC, merged