Learn GraphQL federation
graphql/graphql.github.io pull request #1826
Opened 2024-11-15 10:30 UTC by kamilkisiela

I thought about creating a page that explains what federation in context of GraphQL even means,
to create a good entry point for people interested in this space and looking for information.
It could help to shine more light on Composite Schema Working Group and the spec that's in progress.

The WG would have a page to explain what, how and why.

---

It's an initial draft, something to iterate on, think what to include etc. Happy to hear your thoughts.

2024-11-21 11:57 UTC, kamilkisiela commented on src/pages/learn/federation.mdx
> +Apollo GraphQL, ChilliCream, Google, Graphile, The Guild, Hasura, and IBM,
```suggestion
Apollo GraphQL, ChilliCream, Netflix, Graphile, The Guild, and Hasura,
```

2024-11-21 15:36 UTC, Urigo approved these changes

2024-11-22 20:39 UTC, andrewicarlson approved these changes
This looks great! I added some suggestions that I thought helped clarify some specific points or drive the metaphors around federation home.

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +This is where federation comes into play - an architectural pattern that has found particular resonance in the GraphQL ecosystem.
I wonder if reorganizing this intro would make it land a little clearer for folks unfamiliar with Federation. For example: Problem -> parallel solution (metaphor) -> How it relates to Federation.

```suggestion
As applications grow more complex, traditional monolithic approaches often fall short. At scale, monolithic architectures can become cumbersome, brittle, and increasingly hard to test and validate. This has led to a rise in the adoption of new patterns like distributed systems and microservices. In some ways, GraphQL Federation is like microservices for GraphQL – an architectural pattern that has found particular resonance in the GraphQL ecosystem.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +helping establish federation as a standard architectural pattern in the GraphQL ecosystem.
```suggestion
helping establish federation as a standard architectural pattern for building a distributed graph in the GraphQL ecosystem.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +The GraphQL ecosystem is moving towards standardization of federation patterns.
```suggestion
With more companies and developers seeing the benefits of building a distributed graph with federation, the GraphQL ecosystem is now moving towards standardization of federation patterns.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +Federation is an approach to organizing and managing distributed systems.
```suggestion
Architecturally, federation is an approach to organizing and managing distributed systems.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +- Contribute to a unified API without tight coupling
```suggestion
- Contribute to a unified GraphQL API without tight coupling
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +The magic happens through a federated gateway that acts as the central coordinator, combining these separate schemas into a unified schema that clients can query.
```suggestion
The magic happens through a federated gateway that acts as the central coordinator, composing these separate schemas into a unified schema that clients can query.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +It's more complex than simply merging schemas together, because it needs to handle relationships, detect incompatibilities, and ensure types are properly connected across services.
```suggestion
It's more complex than simply merging schemas together, though, because it needs to handle relationships, detect incompatibilities, and ensure types are properly connected across services and subgraphs.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +often provides caching and performance optimizations.
```suggestion
and often provides caching and performance optimizations.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +do not conflict with other subgraphs in the federation.
```suggestion
do not conflict with other subgraphs.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +Services can be scaled independently based on their specific requirements.
```suggestion
Subgraphs and services can be scaled independently based on their specific requirements.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +Thanks to GraphQL gateway, clients get a single endpoint with unified schema.
```suggestion
Thanks to GraphQL, clients get a single endpoint with unified schema spanning multiple subgraphs.
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +While monolithic GraphQL APIs have their place, federation offers several advantages for larger applications:
```suggestion
While monolithic GraphQL APIs have their place, federated architectures offer several advantages for larger applications:
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +4. **Set Up Gateway**: Deploy a federation gateway to compose and serve the unified schema
```suggestion
4. **Set Up a federated Gateway**: Deploy a federation gateway to compose and serve the unified schema
```

2024-11-22 20:39 UTC, andrewicarlson commented on src/pages/learn/federation.mdx
> +Organizations can gradually migrate from a monolithic to federated GraphQL, one service at a time.
```suggestion
Organizations can gradually migrate from a monolithic to federated GraphQL implementation, one service at a time.
```

2024-12-11 12:09 UTC, michaelstaib approved these changes

2024-12-12 13:08 UTC, benjie commented on src/pages/learn/federation.mdx
> +has found particular resonance in the GraphQL ecosystem.
@mjmahone I'd love to get your input on this paragraph.

2024-12-12 13:38 UTC, benjie requested changes
This looks like an excellent resource; thanks for your work on it!

Please play close attention to capitalisation, for example:

- "GraphQL Federation" - this is a Thing, a technology, because it is a proper noun
- "GraphQL federation" - this is a concept, an approach, it is not a proper noun

Be sure you're using the right version in each case to help the reader interpret your intent.

The capitalisation of subheadings is also inconsistent, we generally use "Sentence case" in headings rather than "Title Case" (checked via `grep -R '^##' src/pages/learn/`) though there are definitely exceptions we should tidy up. Really we should have a style guide for this; if you fancy setting up Vale.sh as a separate PR feel free!

I think we might need to carefully audit usage of the word "graph", and perhaps replace it with "GraphQL schema" or other clearer wording in a few places - for example:

> helping establish federation as a standard architectural pattern for building a distributed graph in the GraphQL ecosystem.

Conceptually you already have a distributed graph (your business entities), and federation is instead an architectural pattern for building a single GraphQL schema that models and enables interaction with your existing distributed graph. (I wouldn't necessarily use this wording in the docs though.)

I like that you've attempted to represent balance via the Meta/Netflix/Volvo/etc comparison; however it should be noted that these companies aren't just "at scale" but are at _hyper_ scale - they are international household names. The vast vast majority of companies and organizations are _not_ at this scale, so I'm concerned that text such as:

> As you see, many industry leaders successfully federated their GraphQL APIs, proving that it works reliably for large-scale production applications.

will encourage smaller organizations to prematurely adopt federated GraphQL techniques thinking that we're recommending it. I think some additional qualifiers might help with this:

> As you see, some of the world's largest industry leaders have successfully federated their GraphQL APIs, proving that it works reliably for production applications at an extraordinary scale.

May also be worth adding text that makes it clear you don't need to start with Federation out of the gate, but can upgrade to it later _when_ you need it (rather than starting with it _just in case_ you need it later).

Overall I think this is excellent content - thanks again for all your efforts!

2024-12-19 15:59 UTC, benjie reviewed
This is excellent; the only part I'm hesitant on is the first three sentences - I'd love some feedback from @graphql/tsc on that paragraph in particular.

Thanks for your work on this @kamilkisiela :raised_hands:

2024-12-19 16:03 UTC, benjie approved these changes
Scratch that; though I'd still welcome the feedback of @mjmahone and @leebyron in particular, the text is accurate: monolithic approachs do _often_ fall short, and they _can_ become cumbersome - they don't always do these things, and there's plenty of examples of monoliths scaling massively just fine, but there's also plenty of counter-examples where microservices/etc are necessary.

2024-12-19 16:22 UTC, kamilkisiela commented
From my experience, there are more examples of broken monoliths than unnecessary usage of Apollo Federation, but I'm fine with adjusting the sentence a bit

2024-12-19 19:10 UTC, andimarek commented
> This is excellent; the only part I'm hesitant on is the first three sentences - I'd love some feedback from @graphql/tsc on that paragraph in particular.


I would recommend to keep this section a bit more neutral. I get the sentiment, but there is no real reason to go into the trade off discussion here.

Something along the lines of "an alternative design approach to the classical monolith, often described as micro services (link to https://martinfowler.com/articles/microservices.html) has gained popularity in the last decade+".

We should not argue for one or the other and leave this discussion to much better pages like the Fowler page.

My 2cent.

2025-01-20 11:11 UTC, kamilkisiela commented on src/pages/learn/federation.mdx
> +has found particular resonance in the GraphQL ecosystem.
```suggestion
An alternative design approach to the classical monolith, often described as microservices, emphasizes breaking down complex systems into smaller, independently managed components. In some ways, GraphQL federation is like microservices for GraphQL - an architectural pattern that has found particular resonance in the GraphQL ecosystem.
```

2025-01-20 11:12 UTC, kamilkisiela commented
Ok, the intro got an update

2025-01-23 16:16 UTC, benjie commented
Beautifully worded fix to the first paragraph; great work @kamilkisiela!

2025-01-23 16:16 UTC, benjie approved these changes

2025-01-23 18:49 UTC, merged

2025-01-23 23:45 UTC, bignimbus reviewed
+1