Update best practices docs
graphql/graphql.github.io pull request #1838
Opened 2024-11-28 17:23 UTC by mandiwise

## Description

This PR provides an updated format for the top-level [/learn/best-practices/](https://graphql.org/learn/best-practices/) page. Much of the content from this page was incorporated into the revised sub-pages in this section during the docs overhaul project. The new formatting leverages the card-based layout used on other Community pages to direct visitors to the topical sub-pages instead of duplicating/summarizing the content here again.

@benjie @jorydotcom

2024-11-28 17:39 UTC, benjie requested changes

2024-11-28 17:39 UTC, benjie commented on src/pages/learn/schema-design.mdx
> +While there's nothing that prevents a GraphQL service from being versioned just like any other REST API, GraphQL takes a strong opinion on avoiding versioning by providing the tools for the continuou
```suggestion
While there's nothing that prevents a GraphQL service from being versioned just like any other API, GraphQL takes a strong opinion on avoiding versioning by providing the tools for the continuous evolution of a GraphQL schema.
```

2024-11-28 17:39 UTC, benjie commented on src/pages/learn/schema-design.mdx
> +In contrast, GraphQL only returns the data that's explicitly requested, so new capabilities can be added via new types and new fields on those types without creating a breaking change. This has led t
```suggestion
In contrast, GraphQL only returns the data that's explicitly requested, so new capabilities can be added via new types or new fields on existing types without creating a breaking change. This has led to a common practice of always avoiding breaking changes and serving a versionless API.
```

2024-11-28 17:39 UTC, benjie approved these changes
Looks good to me - thanks, @mandiwise! :raised_hands:

2024-11-29 22:21 UTC, saihaj approved these changes

2024-12-12 14:16 UTC, merged