Fix docs for GraphQL.NET 3.0.0 release
graphql/graphql.github.io pull request #914
Opened 2020-09-13 09:50 UTC by sungam3r

See https://github.com/graphql-dotnet/graphql-dotnet/issues/1843

2020-09-13 09:53 UTC, sungam3r commented
@IvanGoncharov @leebyron Could you please review? GraphQL.NET received a long-awaited update to version 3.0.0 and it took a little change in the documentation.

2020-10-26 19:26 UTC, JVimes commented
@sungam3r, I believe there are a few issues:
* I don't think these changes compile. Try following your documentation as if you were a new user.
* Your changes don't fix the exception in the [original issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/1843). See [this comment](https://github.com/graphql-dotnet/graphql-dotnet/issues/1843#issuecomment-691457828).
* Shouldn't this merge request change the [source documentation](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/docs2)? Did you follow the [publishing instructions](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/README.md#publishing)?

2020-10-26 19:59 UTC, sungam3r commented
> I don't think these changes compile. Try following your documentation as if you were a new user.
![изображение](https://user-images.githubusercontent.com/21261007/97221970-b0200880-17de-11eb-919c-9c198da6f70f.png)

> Your changes don't fix the exception in the original issue. See this comment.

😕 

> Shouldn't this merge request change the source documentation? Did you follow the publishing instructions?

Our own documentation http://graphql-dotnet.github.io is now updated automatically after migrating to GitHub Actions.

2020-10-26 20:01 UTC, joemcbride requested changes

2020-10-26 20:01 UTC, joemcbride commented on site/code/index.html.js
> +// AllowSynchronousIO to true which isn't recommended.
```
AllowSynchronousIO ...
```

This comment pertains to ASP.NET Core, which isn't this example of a Console application.  I don't think we need to add this comment here.

2020-10-26 20:03 UTC, joemcbride commented
@sungam3r I think it's much more intuitive to use async/await.

2020-10-26 20:11 UTC, sungam3r commented
OK, changed.

2020-10-26 20:24 UTC, JVimes commented
@sungam3r What version are you on? It does not work for me:

![image](https://user-images.githubusercontent.com/6148201/97224554-e89bf400-1796-11eb-9c4a-26efe5c41ea2.png)

2020-10-26 21:24 UTC, Shane32 commented
You need to import a serialization library as well, such as `GraphQL.SystemTextJson`, or else pass an implementation of `IDocumentWriter` to the extension method.

2020-10-26 21:31 UTC, sungam3r commented
@JVimes 
![изображение](https://user-images.githubusercontent.com/21261007/97230832-af41a380-17eb-11eb-8734-cd5cc45dece5.png)

OK?

2020-10-26 22:06 UTC, joemcbride approved these changes

2020-10-27 02:01 UTC, JVimes commented
@Shane32 and @sunapi386 -- No, GraphQL.SystemTextJson is *not* part of the hello world code sample! Look for yourself [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/introduction.md) and [here](https://graphql.org/code/#c-net) and [here](https://graphql-dotnet.github.io/docs/getting-started/introduction/). The code sample does not have a `using` statement to bring in the ExecuteAsync extension method. Did you understand the [bug report](https://github.com/graphql-dotnet/graphql-dotnet/issues/1843)? The code sample does not work!

2020-10-27 03:29 UTC, Shane32 commented
> No, GraphQL.SystemTextJson is _not_ part of the hello world code sample! Look for yourself [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/introduction.md) and [here](https://graphql.org/code/#c-net) and [here](https://graphql-dotnet.github.io/docs/getting-started/introduction/). The code sample does not have a `using` statement to bring in the ExecuteAsync extension method. Did you understand the [bug report](https://github.com/graphql-dotnet/graphql-dotnet/issues/1843)? The code sample does not work.

You're correct.  The documentation is wrong, both in this library, and in the graphql-dotnet project samples, for version 3.0.  Keep in mind that unlike version 2.4, the json serialization library has been split off from the main project into separate nuget packages, and you will need one of them to make any practical use of the library - you'd need either `GraphQL.SystemTextJson` or `GraphQL.NewtonsoftJson` for a sample as small as the "hello world" sample shown.

In addition to the PR here to fix the sample shown [here](https://graphql.org/code/#c-net), we will need a PR in the graphql-dotnet repo to fix the file [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/introduction.md) which when published will update the documentation [here](https://graphql-dotnet.github.io/docs/getting-started/introduction/).  Thank you for pointing this out to us.

2020-10-27 17:11 UTC, JVimes commented
Thank you. I think this will really help.

2020-11-18 14:16 UTC, orta commented
I'm going to close this PR as these changes were manually merged upstream by @ardatan in #936 - thanks for updating the list. 

Note: We now [have markdown files](https://github.com/graphql/graphql.github.io/tree/source/src/content/code) which allow for longer descriptions on the new code page: https://graphql.org/code/ - so it'd be awesome if you added some code samples etc to help any project on the page shine.

2020-11-18 14:16 UTC, closed without merging